apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3ivw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zylw-tenant/rhtap-demo-app/hacbs-test-project-3ivw@sha256:65d13d3b7045a957b9c91f6fb287765e6b48ed8e4b2eead4e8ad4d2a3f0e2949
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
